# Generated by Django 3.1.5 on 2021-01-20 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20210119_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pieceofnews',
            options={'ordering': ('date',), 'verbose_name': 'Piece of news', 'verbose_name_plural': 'News'},
        ),
    ]
