# Generated by Django 3.1.5 on 2021-01-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20210120_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceofnews',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
    ]
